### ISSUE TITLE
No compatible version error when buildpack doesn't contain the newest available version

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-publish#161]
## What happened?

* What were you attempting to do?

Building and running an app image ([console app](https://github.com/paketo-buildpacks/dotnet-publish/tree/main/integration/testdata/console_app)) that contains a `console.csproj` file with `<RuntimeFrameworkVersion>2.1.*</RuntimeFrameworkVersion>` in it.

* What did you expect to happen?

The container to successfully run, using the versions specified by the buildpacks.

* What was the actual behavior? Please provide log output, if possible.

I used the `dotnet-core v0.1.3` language family buildpack  to build the app image. It selected `dotnet-runtime version (using console.csproj): 2.1.25`, the latest 2.1 version supported in the buildpack as expected.

Then, I ran `docker run -it -p 8080:8080 console` and it errored with:
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.26' was not found.
  - Check application dependencies and target a framework version installed at:
      /workspace/.dotnet_root/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.25 at [/workspace/.dotnet_root/shared/Microsoft.NETCore.App]
```

When running the container, the error message shows that `2.1.26` is pulled in. This is pulled in by the .NET CLI itself, since that is the most current version available. When using the buildpacks, I would expect that the version the buildpack is pulling in would be the one that ends up on the image. We should find a way to avoid having the .NET CLI overruling the version selection.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

pack `0.17.0`

* What buildpacks are you using? Please include versions.

dotnet-core v0.1.3

## Checklist

* [X] I have included log output.
* [X] The log output includes an error message.
* [X] I have included steps for reproduction.

**Comment by fg-j** [comment]
.NET 2.1 is [no longer supported in the buildpack](https://github.com/paketo-buildpacks/dotnet-core/releases#:~:text=Dependencies%3A,280459701eee9f7d9cfea740d45978556fa46753bfc7b858b7c83014ae209083), and so this buildpack always builds a framework-dependent executable by default (see Microsoft [docs](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli) for explanation of different `dotnet` CLI behaviour for different .NET Core SDK versions). Since framework-dependent executables can be invoked directly, without the `dotnet` CLI, this problem no longer crops up for the provided sample app.
