### ISSUE TITLE
Layer reuse between builds

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/dotnet-publish#94]
As a part of the .NET Core re-architecture, we should implement layer reuse in this buildpack so that `dotnet publish` is not run when there are no source code changes between builds

**Comment by fg-j** [comment]
We saw issues in the [go build buildpack](https://github.com/paketo-buildpacks/go-build/issues/120) where caching the binary layer was error-prone. In that buildpack, we decided to remove binary layer caching and rely solely on the go tooling's inbuilt caching to speed up rebuilds.

In a similar vein, I think a wiser approach for dotnet-publish is to try and rely on whatever caching the `dotnet` CLI does to speed rebuilds. Cache locations for the `dotnet` CLI are not well documented, but testing local builds and rebuilds with the `dotnet` CLI shows that rebuilds are significantly faster than first builds. Surely, the `dotnet` CLI is dropping files onto the filesystem _somewhere_ that we can cache and restore.

**Comment by macsux** [comment]
See [Managing the global packages, cache, and temp folders](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders) for location of folders.

Additionally, files that are created in `obj` folder are reused for subsequent builds. They are part of incremental compilation pipline. By default this folder is created as subfolder from where `csproj` being compiled is found. It can be redirected to another location via MSBuild property `BaseIntermediateOutputPath`. Since you're calling msbuild implicitly via `dotnet publish` this parameter can be set like this `dotnet publish -p:BaseIntermediateOutputPath=some/folder`
